# Generated by Django 2.2.10 on 2020-03-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20200301_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
